// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_verification.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanUpExpiredUserVerifications = `-- name: CleanUpExpiredUserVerifications :exec
DELETE FROM user_verifications
WHERE expires_at < now()
`

func (q *Queries) CleanUpExpiredUserVerifications(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanUpExpiredUserVerificationsStmt, cleanUpExpiredUserVerifications)
	return err
}

const createUserVerification = `-- name: CreateUserVerification :exec
INSERT INTO user_verifications (request_type, user_id, email, verification_code, expires_at)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    ) ON CONFLICT (request_type, user_id, email) DO
UPDATE
SET verification_code = $4
`

type CreateUserVerificationParams struct {
	RequestType      UserVerificationRequestType `json:"request_type"`
	UserID           uuid.UUID                   `json:"user_id"`
	Email            string                      `json:"email"`
	VerificationCode []byte                      `json:"verification_code"`
	ExpiresAt        time.Time                   `json:"expires_at"`
}

func (q *Queries) CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) error {
	_, err := q.exec(ctx, q.createUserVerificationStmt, createUserVerification,
		arg.RequestType,
		arg.UserID,
		arg.Email,
		arg.VerificationCode,
		arg.ExpiresAt,
	)
	return err
}

const deleteUserVerificationsByEmail = `-- name: DeleteUserVerificationsByEmail :exec
DELETE FROM user_verifications
WHERE request_type = $1
    AND email = $2
`

type DeleteUserVerificationsByEmailParams struct {
	RequestType UserVerificationRequestType `json:"request_type"`
	Email       string                      `json:"email"`
}

func (q *Queries) DeleteUserVerificationsByEmail(ctx context.Context, arg DeleteUserVerificationsByEmailParams) error {
	_, err := q.exec(ctx, q.deleteUserVerificationsByEmailStmt, deleteUserVerificationsByEmail, arg.RequestType, arg.Email)
	return err
}

const deleteUserVerificationsByUserID = `-- name: DeleteUserVerificationsByUserID :exec
DELETE FROM user_verifications
WHERE request_type = $1
    AND user_id = $2
`

type DeleteUserVerificationsByUserIDParams struct {
	RequestType UserVerificationRequestType `json:"request_type"`
	UserID      uuid.UUID                   `json:"user_id"`
}

func (q *Queries) DeleteUserVerificationsByUserID(ctx context.Context, arg DeleteUserVerificationsByUserIDParams) error {
	_, err := q.exec(ctx, q.deleteUserVerificationsByUserIDStmt, deleteUserVerificationsByUserID, arg.RequestType, arg.UserID)
	return err
}

const getUserVerificationByEmail = `-- name: GetUserVerificationByEmail :one
SELECT request_type, user_id, email, verification_code, expires_at, created_at
FROM user_verifications
WHERE request_type = $1
    AND email = $2
    AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetUserVerificationByEmailParams struct {
	RequestType UserVerificationRequestType `json:"request_type"`
	Email       string                      `json:"email"`
}

func (q *Queries) GetUserVerificationByEmail(ctx context.Context, arg GetUserVerificationByEmailParams) (UserVerification, error) {
	row := q.queryRow(ctx, q.getUserVerificationByEmailStmt, getUserVerificationByEmail, arg.RequestType, arg.Email)
	var i UserVerification
	err := row.Scan(
		&i.RequestType,
		&i.UserID,
		&i.Email,
		&i.VerificationCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserVerificationByUserID = `-- name: GetUserVerificationByUserID :one
SELECT request_type, user_id, email, verification_code, expires_at, created_at
FROM user_verifications
WHERE request_type = $1
    AND user_id = $2
    AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetUserVerificationByUserIDParams struct {
	RequestType UserVerificationRequestType `json:"request_type"`
	UserID      uuid.UUID                   `json:"user_id"`
}

func (q *Queries) GetUserVerificationByUserID(ctx context.Context, arg GetUserVerificationByUserIDParams) (UserVerification, error) {
	row := q.queryRow(ctx, q.getUserVerificationByUserIDStmt, getUserVerificationByUserID, arg.RequestType, arg.UserID)
	var i UserVerification
	err := row.Scan(
		&i.RequestType,
		&i.UserID,
		&i.Email,
		&i.VerificationCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationByUserIDAndEmail = `-- name: GetVerificationByUserIDAndEmail :one
SELECT request_type, user_id, email, verification_code, expires_at, created_at
FROM user_verifications
WHERE request_type = $1
    AND user_id = $2
    AND email = $3
    AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetVerificationByUserIDAndEmailParams struct {
	RequestType UserVerificationRequestType `json:"request_type"`
	UserID      uuid.UUID                   `json:"user_id"`
	Email       string                      `json:"email"`
}

func (q *Queries) GetVerificationByUserIDAndEmail(ctx context.Context, arg GetVerificationByUserIDAndEmailParams) (UserVerification, error) {
	row := q.queryRow(ctx, q.getVerificationByUserIDAndEmailStmt, getVerificationByUserIDAndEmail, arg.RequestType, arg.UserID, arg.Email)
	var i UserVerification
	err := row.Scan(
		&i.RequestType,
		&i.UserID,
		&i.Email,
		&i.VerificationCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
